"""Add active column to contracts table

Revision ID: cbe772ef7868
Revises: 3fda536f17fc
Create Date: 2024-06-20 01:09:08.581074

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cbe772ef7868'
down_revision: Union[str, None] = '3fda536f17fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'active')
    # ### end Alembic commands ###
